export default [
  { domain: "1e2.ir" },
  { domain: "1e3.ir" },
  { domain: "4ord.ir" },
  { domain: "activ8.ir" },
  { domain: "andbrands.ir" },
  { domain: "algida.ir", name: "الگیدا" },
  { domain: "acenayman.ir", name: "Ace Nayman" },
  { domain: "atasun.ir", name: "آتاسان اپتیک" },
  { domain: "avansas.ir", name: "آوانساس" },
  { domain: "badbear.ir", name: "بد بیر" },
  { domain: "barcin.ir", name: "بارچین" },
  { domain: "bellamaison.ir", name: "بلا میسون" },
  { domain: "benri.ir", name: "بنری" },
  { domain: "bobletea.ir", name: "بابل تی" },
  { domain: "calve.ir", name: "Calve" },
  { domain: "carboon.ir" },
  { domain: "catit.ir", name: "کتیت" },
  { domain: "dimes.ir", name: "دیمس" },
  { domain: "doremusic.ir", name: "دو رِ موزیک" },
  { domain: "dardanel.ir", name: "دردانل" },
  { domain: "deepfresh.ir", name: "دیپ فرش" },
  { domain: "defactofit.ir", name: "دفکتو فیت" },
  { domain: "deichmann.ir", name: "دیچمان", en: "Deichmann" },
  { domain: "doyuyo.ir", name: "Doyuyo" },
  { domain: "dreamies.ir", name: "دریمیز", en: "Dreamies" },
  { domain: "durumle.ir", name: "دورومله" },
  { domain: "ea7.ir", name: "امپریو آرمانی", en: "Emporio Armani" },
  { domain: "e-bebek.ir", name: "ای ببک", en: "ebebek" },
  { domain: "evidea.ir", name: "اویدیا", en: "Evidea" },
  { domain: "eqbali.ir" },
  { domain: "fashfed.ir", name: "فش فد", en: "FashFed" },
  { domain: "ferrerorocher.ir", name: "فررو روچر", en: "Ferrero Rocher" },
  { domain: "flybe.ir" },
  { domain: "gardenmix.ir", name: "گاردن میکس", en: "Garden Mix" },
  { domain: "harras.ir", name: "هراس", en: "Harras" },
  { domain: "hanmadang.ir" },
  { domain: "herschel.ir", name: "هرشل ساپلای" },
  { domain: "happymoons.ir" },
  { domain: "houseofsuperstep.ir", name: "هوس آف سوپر استپ" },
  { domain: "hobix.ir", name: "هابیکس", en: "Hobix" },
  { domain: "homesweethome.ir", name: "هوم سوییت هوم", en: "Home Sweet Home" },
  { domain: "idefix.ir", name: "آیدفیکس", en: "idefix" },
  { domain: "ilovefish.ir" },
  { domain: "indomie.ir", name: "ایندومی", en: "Indomie" },
  { domain: "inveon.ir" },
  { domain: "jackjones.ir", name: "جک اند جونز", en: "Jack & Jones" },
  { domain: "kahvedunyasi.ir", name: "کاهوه دنیاسی", en: "Kahve Dünyası" },
  { domain: "koska.ir", name: "کوسکا", en: "Koska" },
  { domain: "karlkani.ir", name: "کارل کانی", en: "Karl Kani" },
  { domain: "ketab-sefid.ir" },
  { domain: "khodroad.ir" },
  { domain: "kanken.ir", name: "کنکن", en: "Kanken" },
  { domain: "knitss.ir", name: "Knitss", en: "Knitss" },
  { domain: "kumpir.ir", name: "کمپیر", en: "Kumpir" },
  { domain: "lescon.ir", name: "لسکون", en: "Lescon" },
  { domain: "lc-waikiki.ir", name: "ال‌سی وایکیکی", en: "LC Waikiki" },
  { domain: "lesbenjamins.ir", name: "لس بنجامین", en: "Les Benjamins" },
  { domain: "madparfumeur.ir", name: "مد پرفیوم", en: "MAD Parfumeur" },
  { domain: "mahdaneh.ir" },
  { domain: "mahdoneh.ir" },
  { domain: "markpark.ir", name: "مارکا پارک", en: "Marka Park" },
  { domain: "macrocenter.ir", name: "ماکرو سنتر", en: "Macrocenter" },
  { domain: "mahmoodrice.ir", name: "برنج محمود", en: "Mahmood Rice" },
  { domain: "mikelcoffee.ir", name: "مایکل کافی", en: "Mikel Coffee" },
  { domain: "minycenter.ir", name: "مینی سنتر", en: "Minycenter" },
  { domain: "mosyo.ir" },
  { domain: "mugler.ir", name: "موگلر", en: "Mugler" },
  { domain: "muix.ir" },
  { domain: "mukbang.ir" },
  { domain: "manebi.ir", name: "Manebí" },
  { domain: "nilky.ir", name: "نیلکی", en: "Nilky" },
  { domain: "onvo.ir", name: "آنوا", en: "Onvo" },
  { domain: "off-white.ir", name: "آف وایت", en: "Off-White" },
  { domain: "ortopedia.ir", name: "ارتوپدیا", en: "Ortopedia" },
  { domain: "pazarama.ir", name: "پازاراما", en: "Pazarama" },
  { domain: "pidem.ir", name: "پیدم", en: "Pidem" },
  { domain: "pologarage.ir", name: "پولو گاراژ", en: "Pologarage" },
  { domain: "preo.ir", name: "پریو", en: "Preo" },
  { domain: "q11.ir" },
  { domain: "recyclr.ir" },
  { domain: "rentgo.ir" },
  { domain: "savetheduck.ir", name: "سیو دِ داک", en: "Save The Duck" },
  { domain: "sbarro.ir", name: "اسبارو", en: "Sbarro" },
  { domain: "solero.ir", name: "سولرو", en: "Solero" },
  { domain: "schoolcloud.ir" },
  { domain: "sneakscloud.ir", name: "اسنیکس کلاد", en: "Sneaks Cloud" },
  { domain: "sneaksup.ir", name: "اسنیکس آپ", en: "Sneaks Up" },
  { domain: "sooraya.ir" },
  { domain: "solesisters.ir", name: "سول سیسترز", en: "Sole Sisters" },
  { domain: "sportempt.ir", name: "اسپورتمپت", en: "Sportempt" },
  { domain: "sporthink.ir", name: "اسپورتینک", en: "Sporthink" },
  { domain: "sportime.ir", name: "اسپورتایم", en: "Sportime" },
  { domain: "sanalcadir.ir", name: "سانال چادیر", en: "Sanal Çadır" },
  { domain: "sutas.ir", name: "سوتاش" },
  { domain: "sutore.ir" },
  { domain: "saat-saat.ir", name: "ساعت و ساعت", en: "Saat&Saat" },
  { domain: "tadelle.ir", name: "تادله", en: "Tadelle" },
  { domain: "tangleteezer.ir", name: "تنگل تیزر", en: "Tangle Teezer" },
  { domain: "thehundreds.ir", name: "The Hundreds" },
  { domain: "trendyol-milla.ir", name: "ترندیول میلا", en: "Trendyolmilla" },
  { domain: "tomanat.ir" },
  { domain: "ui6.ir" },
  { domain: "united4.ir", name: "یونایتد فور", en: "United4" },
  { domain: "upwoork.ir" },
  { domain: "unitedbrands.ir", name: "یونایتد برندز", en: "United Brands" },
  { domain: "uspoloassn.ir", name: "یو اس پولو", en: "U.S. Polo Assn." },
  { domain: "v11.ir" },
  { domain: "vakkorama.ir", name: "واکوراما", en: "Vakkorama" },
  { domain: "vatancomputer.ir", name: "وطن کامپیوتر" },
  { domain: "vilber.ir" },
  { domain: "vitruta.ir", name: "ویتروتا" },
  { domain: "wilber.ir" },
  { domain: "wilsoon.ir", name: "ویلسون" },
  { domain: "woodesk.ir", name: "Woodesk" },
  { domain: "wunder.ir", name: "WUNDER" },
  { domain: "xddesign.ir", name: "ایکس دی دیزاین" },
];
