export default [
  { domain: "1e2.ir" },
  { domain: "1e3.ir" },
  { domain: "4ord.ir" },
  { domain: "activ8.ir" },
  { domain: "axess.ir" },
  { domain: "andbrands.ir" },
  { domain: "armalife.ir", name: "آرما لایف", en: "Armalife" },
  { domain: "asperox.ir", name: "آسپروکس", en: "Asperox" },
  { domain: "algida.ir", name: "الگیدا", en: "Algida" },
  { domain: "acenayman.ir", name: "Ace Nayman" },
  { domain: "atasun.ir", name: "آتاسان اپتیک", en: "Atasun Optik" },
  { domain: "avansas.ir", name: "آوانساس", en: "Avansas" },
  { domain: "badbear.ir", name: "بد بیر", en: "Bad Bear" },
  { domain: "barcin.ir", name: "بارچین", en: "Barçın" },
  { domain: "beaulis.ir", name: "بیولیس", en: "Beaulis" },
  { domain: "bellamaison.ir", name: "بلا میسون", en: "Bella Maison" },
  { domain: "benri.ir", name: "بنری", en: "Benri" },
  { domain: "bobletea.ir", name: "بابل تی", en: "Boble Bubble Tea" },
  { domain: "calve.ir", name: "کالو", en: "Calve" },
  { domain: "cornetto.ir", name: "کورنتو", en: "Cornetto" },
  { domain: "carboon.ir" },
  { domain: "catit.ir", name: "کتیت", en: "Catit" },
  { domain: "dimes.ir", name: "دیمس", en: "Dimes" },
  { domain: "drunkelephant.ir", name: "درانک الفنت", en: "Drunk Elephant" },
  { domain: "dailyperfection.ir", name: "دیلی پرفکشن", en: "Daily Perfection" },
  {
    domain: "doremusic.ir",
    name: "دو رِ موزیک",
    en: "doremusic",
    sub: ["do-re.ir"],
  },
  { domain: "dardanel.ir", name: "دردانل", en: "Dardanel" },
  { domain: "deepfresh.ir", name: "دیپ فرش", en: "DeepFresh" },
  { domain: "defactofit.ir", name: "دفکتو فیت", en: "DeFactoFIT" },
  { domain: "deichmann.ir", name: "دیچمان", en: "Deichmann" },
  { domain: "doyuyo.ir", name: "دویویو", en: "Doyuyo" },
  { domain: "dreamies.ir", name: "دریمیز", en: "Dreamies" },
  { domain: "durumle.ir", name: "دورومله", en: "Dürümle" },
  { domain: "ea7.ir", name: "امپریو آرمانی", en: "Emporio Armani" },
  { domain: "e-bebek.ir", name: "ای ببک", en: "ebebek" },
  { domain: "evidea.ir", name: "اویدیا", en: "Evidea" },
  { domain: "eqbali.ir" },
  { domain: "furminator.ir", name: "فورمیناتور", en: "FURminator" },
  { domain: "fitmoda.ir", name: "فیت مدا", en: "Fitmoda" },
  { domain: "fashfed.ir", name: "فشفد", en: "FashFed" },
  { domain: "ferrerorocher.ir", name: "فررو روچر", en: "Ferrero Rocher" },
  { domain: "flybe.ir" },
  { domain: "gardenmix.ir", name: "گاردن میکس", en: "Garden Mix" },
  { domain: "harras.ir", name: "هراس", en: "Harras" },
  { domain: "hanmadang.ir" },
  { domain: "herschel.ir", name: "هرشل ساپلای", en: "Herschel Supply" },
  { domain: "happymoons.ir" },
  {
    domain: "houseofsuperstep.ir",
    name: "هوس آف سوپر استپ",
    en: "House of Superstep",
  },
  { domain: "hobix.ir", name: "هابیکس", en: "Hobix" },
  { domain: "hufworldwide.ir", name: "هاف ورلد واید", en: "HUF Worldwide" },
  { domain: "homesweethome.ir", name: "هوم سوییت هوم", en: "Home Sweet Home" },
  { domain: "idefix.ir", name: "آیدفیکس", en: "idefix" },
  { domain: "ilovefish.ir" },
  { domain: "inter-sport.ir", name: "اینتر اسپورت", en: "Intersport" },
  { domain: "indomie.ir", name: "ایندومی", en: "Indomie" },
  { domain: "isbir.ir", name: "ایش بیر", en: "İşbir" },
  { domain: "inveon.ir" },
  {
    domain: "jackjones.ir",
    name: "جک اند جونز",
    en: "Jack & Jones",
    sub: ["jack-jones.ir"],
  },
  { domain: "kahvedunyasi.ir", name: "کاهوه دنیاسی", en: "Kahve Dünyası" },
  { domain: "karlkani.ir", name: "کارل کانی", en: "Karl Kani" },
  { domain: "ketab-sefid.ir" },
  { domain: "khodroad.ir" },
  { domain: "koenic.ir", name: "کونیک", en: "KOENIC" },
  { domain: "kanken.ir", name: "کنکن", en: "Kanken" },
  { domain: "knitss.ir", name: "نیتس", en: "Knitss" },
  { domain: "kumpir.ir", name: "کمپیر", en: "Kumpir" },
  { domain: "lescon.ir", name: "لسکون", en: "Lescon" },
  { domain: "lavital.ir", name: "لاویتال", en: "LaVital" },
  { domain: "lc-waikiki.ir", name: "ال‌سی وایکیکی", en: "LC Waikiki" },
  { domain: "lesbenjamins.ir", name: "لس بنجامین", en: "Les Benjamins" },
  { domain: "madparfumeur.ir", name: "مد پرفیوم", en: "MAD Parfumeur" },
  { domain: "mahdaneh.ir" },
  { domain: "mahdoneh.ir" },
  {
    domain: "madame-coco.ir",
    name: "مادام کوکو",
    en: "Madame Coco",
    sub: ["madam-coco.ir"],
  },
  { domain: "markpark.ir", name: "مارکا پارک", en: "Marka Park" },
  { domain: "macrocenter.ir", name: "ماکرو سنتر", en: "Macrocenter" },
  { domain: "mahmoodrice.ir", name: "برنج محمود", en: "Mahmood Rice" },
  { domain: "mikelcoffee.ir", name: "مایکل کافی", en: "Mikel Coffee" },
  { domain: "minycenter.ir", name: "مینی سنتر", en: "Minycenter" },
  { domain: "mosyo.ir" },
  { domain: "mugler.ir", name: "موگلر", en: "Mugler" },
  { domain: "muix.ir" },
  { domain: "mukbang.ir" },
  { domain: "marketstudios.ir", name: "مارکت استودیوز", en: "Market Studios" },
  { domain: "manebi.ir", name: "مانبی", en: "Manebí" },
  { domain: "nilky.ir", name: "نیلکی", en: "Nilky" },
  { domain: "nasaqu.ir", name: "ناساکو", en: "NASAQU" },
  { domain: "naturessupreme.ir", name: "نیچرز سوپریم", en: "Nature's Supreme" },
  { domain: "onvo.ir", name: "آنوا", en: "Onvo" },
  { domain: "okkia.ir", name: "اوکیا", en: "Okkia" },
  { domain: "off-white.ir", name: "آف وایت", en: "Off-White" },
  { domain: "ortopedia.ir", name: "ارتوپدیا", en: "Ortopedia" },
  { domain: "pazarama.ir", name: "پازاراما", en: "Pazarama" },
  { domain: "pidem.ir", name: "پیدم", en: "Pidem" },
  { domain: "pologarage.ir", name: "پولو گاراژ", en: "Pologarage" },
  { domain: "preo.ir", name: "پریو", en: "Preo" },
  { domain: "q11.ir" },
  { domain: "recyclr.ir" },
  { domain: "rentgo.ir" },
  { domain: "ruckmaul.ir", name: "راک اند مول", en: "Ruck & Maul" },
  { domain: "rossman.ir", name: "رزمن", en: "Rossmann" },
  { domain: "savetheduck.ir", name: "سیو دِ داک", en: "Save The Duck" },
  { domain: "sbarro.ir", name: "اسبارو", en: "Sbarro" },
  { domain: "solero.ir", name: "سولرو", en: "Solero" },
  {
    domain: "sephoracollection.ir",
    name: "سفورا کالکشن",
    en: "Sephora Collection",
  },
  { domain: "schoolcloud.ir" },
  { domain: "sneakscloud.ir", name: "اسنیکس کلاد", en: "Sneaks Cloud" },
  { domain: "sneaksup.ir", name: "اسنیکس آپ", en: "Sneaks Up" },
  { domain: "sooraya.ir" },
  { domain: "solesisters.ir", name: "سول سیسترز", en: "Sole Sisters" },
  { domain: "sportempt.ir", name: "اسپورتمپت", en: "Sportempt" },
  { domain: "sporthink.ir", name: "اسپورتینک", en: "Sporthink" },
  { domain: "sportime.ir", name: "اسپورتایم", en: "Sportime" },
  { domain: "sanalcadir.ir", name: "سانال چادیر", en: "Sanal Çadır" },
  { domain: "sutas.ir", name: "سوتاش", en: "Sütaş" },
  { domain: "sutore.ir", name: "سوتور", en: "sutore" },
  { domain: "super-step.ir", name: "سوپر استپ", en: "SuperStep" },
  { domain: "super-kids.ir", name: "سوپر کیدز", en: "SuperKids" },
  { domain: "sneakerbaker.ir", name: "اسنیکر بیکر", en: "Sneaker Baker" },
  { domain: "saat-saat.ir", name: "ساعت و ساعت", en: "Saat&Saat" },
  { domain: "tadelle.ir", name: "تادله", en: "Tadelle" },
  { domain: "tommy-hilfiger.ir", name: "تامی هیلفیگر", en: "Tommy Hilfiger" },
  { domain: "tangleteezer.ir", name: "تنگل تیزر", en: "Tangle Teezer" },
  { domain: "thehundreds.ir", name: "دِ هاندردز", en: "The Hundreds" },
  { domain: "trendyol-milla.ir", name: "ترندیول میلا", en: "Trendyolmilla" },
  {
    domain: "toyzzshop.ir",
    name: "تویز شاپ",
    en: "Toyzz Shop",
    sub: ["toyzshop.ir"],
  },
  { domain: "thepurest.ir", name: "دِ پیورست", en: "The Purest" },
  { domain: "tomanat.ir" },
  { domain: "ui6.ir" },
  { domain: "united4.ir", name: "یونایتد فور", en: "United4" },
  { domain: "upwoork.ir" },
  { domain: "unitedbrands.ir", name: "یونایتد برندز", en: "United Brands" },
  { domain: "uspoloassn.ir", name: "یو اس پولو", en: "U.S. Polo Assn." },
  { domain: "v11.ir" },
  { domain: "vakkorama.ir", name: "واکوراما", en: "Vakkorama" },
  {
    domain: "vatancomputer.ir",
    name: "وطن کامپیوتر",
    en: "Vatan Computer",
    sub: ["vatan-computer.ir"],
  },
  { domain: "vilber.ir" },
  { domain: "vitruta.ir", name: "ویتروتا", en: "vitruta" },
  { domain: "wilber.ir" },
  { domain: "vitaminler.ir", name: "ویتامینلر", en: "Vitaminler" },
  { domain: "wilsoon.ir", name: "ویلسون", name: "Wilson" },
  { domain: "woodesk.ir", name: "وودسک", en: "Woodesk" },
  { domain: "wunder.ir", name: "واندر", en: "WUNDER" },
  { domain: "zsazsazsu.ir", name: "Zsa Zsa Zsu" },
  { domain: "xddesign.ir", name: "ایکس دی دیزاین", en: "XD Design" },
];
