export default [
  { domain: "1e2.ir" },
  { domain: "1e3.ir" },
  { domain: "4ord.ir" },
  { domain: "activ8.ir" },
  { domain: "andbrands.ir" },
  { domain: "acenayman.ir", name: "Ace Nayman" },
  { domain: "atasun.ir", name: "آتاسان اپتیک" },
  { domain: "avansas.ir", name: "آوانساس" },
  { domain: "badbear.ir", name: "بد بیر" },
  { domain: "barcin.ir", name: "بارچین" },
  { domain: "bellamaison.ir", name: "بلا میسون" },
  { domain: "benri.ir", name: "بنری" },
  { domain: "bobletea.ir", name: "بابل تی" },
  { domain: "calve.ir", name: "کالو" },
  { domain: "carboon.ir" },
  { domain: "catit.ir" },
  { domain: "dardanel.ir" },
  { domain: "deepfresh.ir" },
  { domain: "defactofit.ir" },
  { domain: "deichmann.ir" },
  { domain: "doyuyo.ir" },
  { domain: "dreamies.ir" },
  { domain: "durumle.ir" },
  { domain: "ea7.ir", name: "امپریو آرمانی" },
  { domain: "eqbali.ir" },
  { domain: "fashfed.ir", name: "فشفد" },
  { domain: "ferrerorocher.ir" },
  { domain: "flybe.ir" },
  { domain: "gardenmix.ir" },
  { domain: "hanmadang.ir" },
  { domain: "happymoons.ir" },
  { domain: "hobix.ir", name: "هابیکس" },
  { domain: "homesweethome.ir", name: "هوم سوییت هوم" },
  { domain: "idefix.ir" },
  { domain: "ilovefish.ir" },
  { domain: "indomie.ir" },
  { domain: "inveon.ir" },
  { domain: "jackjones.ir", name: "جک اند جونز" },
  { domain: "kahvedunyasi.ir" },
  { domain: "karlkani.ir", name: "کارل کانی" },
  { domain: "ketab-sefid.ir" },
  { domain: "khodroad.ir" },
  { domain: "kumpir.ir", name: "کمپیر" },
  { domain: "lescon.ir", name: "لسکون" },
  { domain: "lesbenjamins.ir", name: "لس بنجامین" },
  { domain: "madparfumeur.ir" },
  { domain: "mahdaneh.ir" },
  { domain: "mahdoneh.ir" },
  { domain: "mahmoodrice.ir", name: "برنج محمود" },
  { domain: "mikelcoffee.ir" },
  { domain: "minycenter.ir" },
  { domain: "mosyo.ir" },
  { domain: "mugler.ir", name: "موگلر" },
  { domain: "muix.ir" },
  { domain: "mukbang.ir" },
  { domain: "manebi.ir", name: "Manebí" },
  { domain: "onvo.ir" },
  { domain: "off-white.ir", name: "Off-White" },
  { domain: "ortopedia.ir", name: "ارتوپدیا" },
  { domain: "pazarama.ir" },
  { domain: "pidem.ir" },
  { domain: "pologarage.ir", name: "پولو گاراژ" },
  { domain: "preo.ir", name: "Preo" },
  { domain: "q11.ir" },
  { domain: "recyclr.ir" },
  { domain: "rentgo.ir" },
  { domain: "savetheduck.ir" },
  { domain: "sbarro.ir", name: "اسبارو" },
  { domain: "schoolcloud.ir" },
  { domain: "sneakscloud.ir", name: "اسنیکس کلاد" },
  { domain: "sneaksup.ir", name: "اسنیکس آپ" },
  { domain: "sooraya.ir" },
  { domain: "sportempt.ir" },
  { domain: "sporthink.ir" },
  { domain: "sportime.ir" },
  { domain: "sutore.ir" },
  { domain: "tadelle.ir", name: "تادله" },
  { domain: "tangleteezer.ir", name: "تنگل تیزر" },
  { domain: "thehundreds.ir", name: "The Hundreds" },
  { domain: "trendyol-milla.ir", name: "ترندیول میلا" },
  { domain: "tomanat.ir" },
  { domain: "ui6.ir" },
  { domain: "united4.ir", name: "یونایتد4" },
  { domain: "upwoork.ir" },
  { domain: "uspoloassn.ir", name: "یو اس پولو" },
  { domain: "v11.ir" },
  { domain: "vakkorama.ir", name: "واکوراما" },
  { domain: "vatancomputer.ir" },
  { domain: "vilber.ir" },
  { domain: "vitruta.ir" },
  { domain: "wilber.ir" },
  { domain: "wilsoon.ir", name: "ویلسون" },
  { domain: "woodesk.ir", name: "Woodesk" },
  { domain: "wunder.ir", name: "WUNDER" },
  { domain: "xddesign.ir", name: "ایکس دی دیزاین" },
];
